-- Hockey Star Quiz leaderboard (run in Supabase SQL editor)
create table if not exists public.hockey_star_quiz_scores (
  id bigint generated by default as identity primary key,
  player_id uuid not null references public.players(id) on delete cascade,
  player_name text not null,
  player_avatar text,
  score bigint not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists hockey_star_quiz_scores_player_id_idx
  on public.hockey_star_quiz_scores (player_id);

create index if not exists hockey_star_quiz_scores_score_idx
  on public.hockey_star_quiz_scores (score desc);

alter table public.hockey_star_quiz_scores enable row level security;

drop policy if exists "Anyone can read quiz scores" on public.hockey_star_quiz_scores;
create policy "Anyone can read quiz scores"
  on public.hockey_star_quiz_scores for select
  using (true);

drop policy if exists "Authenticated users insert own quiz scores" on public.hockey_star_quiz_scores;
drop policy if exists "Anyone can insert quiz scores for valid player" on public.hockey_star_quiz_scores;
drop policy if exists "Anyone can insert quiz scores" on public.hockey_star_quiz_scores;
create policy "Anyone can insert quiz scores"
  on public.hockey_star_quiz_scores for insert
  with check (true);

grant select, insert on public.hockey_star_quiz_scores to anon;
grant select, insert on public.hockey_star_quiz_scores to authenticated;
grant all on public.hockey_star_quiz_scores to service_role;
