// Типы для упражнений
export interface Exercise {
  id: string;
  titleKey: string; // Ключ для перевода названия
  descriptionKey: string; // Ключ для перевода описания
  categoryKey: string; // Ключ для перевода категории
  duration: string;
  difficultyKey: string; // Ключ для перевода сложности
  image?: string;
}

// Данные упражнений
export const exercisesData: Exercise[] = [
  // Выносливость
  {
    id: '1',
    titleKey: 'exercises.items.1.title',
    descriptionKey: 'exercises.items.1.description',
    categoryKey: 'exercises.categories.Выносливость',
    duration: '20-30 мин',
    difficultyKey: 'exercises.difficulty.Средний',
  },
  {
    id: '2',
    titleKey: 'exercises.items.2.title',
    descriptionKey: 'exercises.items.2.description',
    categoryKey: 'exercises.categories.Выносливость',
    duration: '15-20 мин',
    difficultyKey: 'exercises.difficulty.Продвинутый',
  },
  {
    id: '3',
    titleKey: 'exercises.items.3.title',
    descriptionKey: 'exercises.items.3.description',
    categoryKey: 'exercises.categories.Выносливость',
    duration: '25-30 мин',
    difficultyKey: 'exercises.difficulty.Средний',
  },
  {
    id: '16',
    titleKey: 'exercises.items.16.title',
    descriptionKey: 'exercises.items.16.description',
    categoryKey: 'exercises.categories.Выносливость',
    duration: '25-30 мин',
    difficultyKey: 'exercises.difficulty.Средний',
  },
  {
    id: '17',
    titleKey: 'exercises.items.17.title',
    descriptionKey: 'exercises.items.17.description',
    categoryKey: 'exercises.categories.Выносливость',
    duration: '20 мин',
    difficultyKey: 'exercises.difficulty.Средний',
  },
  {
    id: '18',
    titleKey: 'exercises.items.18.title',
    descriptionKey: 'exercises.items.18.description',
    categoryKey: 'exercises.categories.Выносливость',
    duration: '20-25 мин',
    difficultyKey: 'exercises.difficulty.Продвинутый',
  },
  {
    id: '19',
    titleKey: 'exercises.items.19.title',
    descriptionKey: 'exercises.items.19.description',
    categoryKey: 'exercises.categories.Выносливость',
    duration: '15 мин',
    difficultyKey: 'exercises.difficulty.Средний',
  },
  {
    id: '20',
    titleKey: 'exercises.items.20.title',
    descriptionKey: 'exercises.items.20.description',
    categoryKey: 'exercises.categories.Выносливость',
    duration: '15 мин',
    difficultyKey: 'exercises.difficulty.Начинающий',
  },

  // Взрывная скорость
  {
    id: '4',
    titleKey: 'exercises.items.4.title',
    descriptionKey: 'exercises.items.4.description',
    categoryKey: 'exercises.categories.Взрывная скорость',
    duration: '10-15 мин',
    difficultyKey: 'exercises.difficulty.Средний',
  },
  {
    id: '5',
    titleKey: 'exercises.items.5.title',
    descriptionKey: 'exercises.items.5.description',
    categoryKey: 'exercises.categories.Взрывная скорость',
    duration: '15-20 мин',
    difficultyKey: 'exercises.difficulty.Начинающий',
  },
  {
    id: '6',
    titleKey: 'exercises.items.6.title',
    descriptionKey: 'exercises.items.6.description',
    categoryKey: 'exercises.categories.Взрывная скорость',
    duration: '15 мин',
    difficultyKey: 'exercises.difficulty.Средний',
  },
  {
    id: '21',
    titleKey: 'exercises.items.21.title',
    descriptionKey: 'exercises.items.21.description',
    categoryKey: 'exercises.categories.Взрывная скорость',
    duration: '12 мин',
    difficultyKey: 'exercises.difficulty.Средний',
  },
  {
    id: '22',
    titleKey: 'exercises.items.22.title',
    descriptionKey: 'exercises.items.22.description',
    categoryKey: 'exercises.categories.Взрывная скорость',
    duration: '15 мин',
    difficultyKey: 'exercises.difficulty.Продвинутый',
  },
  {
    id: '23',
    titleKey: 'exercises.items.23.title',
    descriptionKey: 'exercises.items.23.description',
    categoryKey: 'exercises.categories.Взрывная скорость',
    duration: '15 мин',
    difficultyKey: 'exercises.difficulty.Продвинутый',
  },
  {
    id: '24',
    titleKey: 'exercises.items.24.title',
    descriptionKey: 'exercises.items.24.description',
    categoryKey: 'exercises.categories.Взрывная скорость',
    duration: '12 мин',
    difficultyKey: 'exercises.difficulty.Средний',
  },
  {
    id: '25',
    titleKey: 'exercises.items.25.title',
    descriptionKey: 'exercises.items.25.description',
    categoryKey: 'exercises.categories.Взрывная скорость',
    duration: '15 мин',
    difficultyKey: 'exercises.difficulty.Продвинутый',
  },

  // Разминка
  {
    id: '7',
    titleKey: 'exercises.items.7.title',
    descriptionKey: 'exercises.items.7.description',
    categoryKey: 'exercises.categories.Разминка',
    duration: '10 мин',
    difficultyKey: 'exercises.difficulty.Начинающий',
  },
  {
    id: '8',
    titleKey: 'exercises.items.8.title',
    descriptionKey: 'exercises.items.8.description',
    categoryKey: 'exercises.categories.Разминка',
    duration: '8-10 мин',
    difficultyKey: 'exercises.difficulty.Начинающий',
  },
  {
    id: '9',
    titleKey: 'exercises.items.9.title',
    descriptionKey: 'exercises.items.9.description',
    categoryKey: 'exercises.categories.Разминка',
    duration: '5-7 мин',
    difficultyKey: 'exercises.difficulty.Начинающий',
  },
  {
    id: '26',
    titleKey: 'exercises.items.26.title',
    descriptionKey: 'exercises.items.26.description',
    categoryKey: 'exercises.categories.Разминка',
    duration: '5 мин',
    difficultyKey: 'exercises.difficulty.Начинающий',
  },
  {
    id: '27',
    titleKey: 'exercises.items.27.title',
    descriptionKey: 'exercises.items.27.description',
    categoryKey: 'exercises.categories.Разминка',
    duration: '3 мин',
    difficultyKey: 'exercises.difficulty.Начинающий',
  },
  {
    id: '28',
    titleKey: 'exercises.items.28.title',
    descriptionKey: 'exercises.items.28.description',
    categoryKey: 'exercises.categories.Разминка',
    duration: '5 мин',
    difficultyKey: 'exercises.difficulty.Начинающий',
  },
  {
    id: '29',
    titleKey: 'exercises.items.29.title',
    descriptionKey: 'exercises.items.29.description',
    categoryKey: 'exercises.categories.Разминка',
    duration: '4 мин',
    difficultyKey: 'exercises.difficulty.Начинающий',
  },
  {
    id: '30',
    titleKey: 'exercises.items.30.title',
    descriptionKey: 'exercises.items.30.description',
    categoryKey: 'exercises.categories.Разминка',
    duration: '5 мин',
    difficultyKey: 'exercises.difficulty.Начинающий',
  },

  // Растяжка
  {
    id: '10',
    titleKey: 'exercises.items.10.title',
    descriptionKey: 'exercises.items.10.description',
    categoryKey: 'exercises.categories.Растяжка',
    duration: '15 мин',
    difficultyKey: 'exercises.difficulty.Начинающий',
  },
  {
    id: '11',
    titleKey: 'exercises.items.11.title',
    descriptionKey: 'exercises.items.11.description',
    categoryKey: 'exercises.categories.Растяжка',
    duration: '12-15 мин',
    difficultyKey: 'exercises.difficulty.Начинающий',
  },
  {
    id: '12',
    titleKey: 'exercises.items.12.title',
    descriptionKey: 'exercises.items.12.description',
    categoryKey: 'exercises.categories.Растяжка',
    duration: '20 мин',
    difficultyKey: 'exercises.difficulty.Средний',
  },
  {
    id: '31',
    titleKey: 'exercises.items.31.title',
    descriptionKey: 'exercises.items.31.description',
    categoryKey: 'exercises.categories.Растяжка',
    duration: '10 мин',
    difficultyKey: 'exercises.difficulty.Начинающий',
  },
  {
    id: '32',
    titleKey: 'exercises.items.32.title',
    descriptionKey: 'exercises.items.32.description',
    categoryKey: 'exercises.categories.Растяжка',
    duration: '8 мин',
    difficultyKey: 'exercises.difficulty.Начинающий',
  },
  {
    id: '33',
    titleKey: 'exercises.items.33.title',
    descriptionKey: 'exercises.items.33.description',
    categoryKey: 'exercises.categories.Растяжка',
    duration: '8 мин',
    difficultyKey: 'exercises.difficulty.Начинающий',
  },
  {
    id: '34',
    titleKey: 'exercises.items.34.title',
    descriptionKey: 'exercises.items.34.description',
    categoryKey: 'exercises.categories.Растяжка',
    duration: '10 мин',
    difficultyKey: 'exercises.difficulty.Начинающий',
  },
  {
    id: '35',
    titleKey: 'exercises.items.35.title',
    descriptionKey: 'exercises.items.35.description',
    categoryKey: 'exercises.categories.Растяжка',
    duration: '8 мин',
    difficultyKey: 'exercises.difficulty.Начинающий',
  },

  // Ловкость
  {
    id: '13',
    titleKey: 'exercises.items.13.title',
    descriptionKey: 'exercises.items.13.description',
    categoryKey: 'exercises.categories.Ловкость',
    duration: '15 мин',
    difficultyKey: 'exercises.difficulty.Средний',
  },
  {
    id: '14',
    titleKey: 'exercises.items.14.title',
    descriptionKey: 'exercises.items.14.description',
    categoryKey: 'exercises.categories.Ловкость',
    duration: '10-15 мин',
    difficultyKey: 'exercises.difficulty.Средний',
  },
  {
    id: '15',
    titleKey: 'exercises.items.15.title',
    descriptionKey: 'exercises.items.15.description',
    categoryKey: 'exercises.categories.Ловкость',
    duration: '12 мин',
    difficultyKey: 'exercises.difficulty.Средний',
  },
  {
    id: '36',
    titleKey: 'exercises.items.36.title',
    descriptionKey: 'exercises.items.36.description',
    categoryKey: 'exercises.categories.Ловкость',
    duration: '10 мин',
    difficultyKey: 'exercises.difficulty.Средний',
  },
  {
    id: '37',
    titleKey: 'exercises.items.37.title',
    descriptionKey: 'exercises.items.37.description',
    categoryKey: 'exercises.categories.Ловкость',
    duration: '12 мин',
    difficultyKey: 'exercises.difficulty.Продвинутый',
  },
  {
    id: '38',
    titleKey: 'exercises.items.38.title',
    descriptionKey: 'exercises.items.38.description',
    categoryKey: 'exercises.categories.Ловкость',
    duration: '15 мин',
    difficultyKey: 'exercises.difficulty.Продвинутый',
  },
  {
    id: '39',
    titleKey: 'exercises.items.39.title',
    descriptionKey: 'exercises.items.39.description',
    categoryKey: 'exercises.categories.Ловкость',
    duration: '10 мин',
    difficultyKey: 'exercises.difficulty.Средний',
  },
  {
    id: '40',
    titleKey: 'exercises.items.40.title',
    descriptionKey: 'exercises.items.40.description',
    categoryKey: 'exercises.categories.Ловкость',
    duration: '15 мин',
    difficultyKey: 'exercises.difficulty.Продвинутый',
  },

  // Сила
  {
    id: '41',
    titleKey: 'exercises.items.41.title',
    descriptionKey: 'exercises.items.41.description',
    categoryKey: 'exercises.categories.Сила',
    duration: '20 мин',
    difficultyKey: 'exercises.difficulty.Продвинутый',
  },
  {
    id: '42',
    titleKey: 'exercises.items.42.title',
    descriptionKey: 'exercises.items.42.description',
    categoryKey: 'exercises.categories.Сила',
    duration: '25 мин',
    difficultyKey: 'exercises.difficulty.Продвинутый',
  },
  {
    id: '43',
    titleKey: 'exercises.items.43.title',
    descriptionKey: 'exercises.items.43.description',
    categoryKey: 'exercises.categories.Сила',
    duration: '20 мин',
    difficultyKey: 'exercises.difficulty.Продвинутый',
  },
  {
    id: '44',
    titleKey: 'exercises.items.44.title',
    descriptionKey: 'exercises.items.44.description',
    categoryKey: 'exercises.categories.Сила',
    duration: '15 мин',
    difficultyKey: 'exercises.difficulty.Продвинутый',
  },
  {
    id: '45',
    titleKey: 'exercises.items.45.title',
    descriptionKey: 'exercises.items.45.description',
    categoryKey: 'exercises.categories.Сила',
    duration: '15 мин',
    difficultyKey: 'exercises.difficulty.Продвинутый',
  },

  // Баланс и стабильность
  {
    id: '46',
    titleKey: 'exercises.items.46.title',
    descriptionKey: 'exercises.items.46.description',
    categoryKey: 'exercises.categories.Баланс',
    duration: '10 мин',
    difficultyKey: 'exercises.difficulty.Средний',
  },
  {
    id: '47',
    titleKey: 'exercises.items.47.title',
    descriptionKey: 'exercises.items.47.description',
    categoryKey: 'exercises.categories.Баланс',
    duration: '12 мин',
    difficultyKey: 'exercises.difficulty.Средний',
  },
  {
    id: '48',
    titleKey: 'exercises.items.48.title',
    descriptionKey: 'exercises.items.48.description',
    categoryKey: 'exercises.categories.Баланс',
    duration: '15 мин',
    difficultyKey: 'exercises.difficulty.Продвинутый',
  },
  {
    id: '49',
    titleKey: 'exercises.items.49.title',
    descriptionKey: 'exercises.items.49.description',
    categoryKey: 'exercises.categories.Баланс',
    duration: '20 мин',
    difficultyKey: 'exercises.difficulty.Средний',
  },
  {
    id: '50',
    titleKey: 'exercises.items.50.title',
    descriptionKey: 'exercises.items.50.description',
    categoryKey: 'exercises.categories.Баланс',
    duration: '15 мин',
    difficultyKey: 'exercises.difficulty.Средний',
  },
  {
    id: '51',
    titleKey: 'exercises.items.51.title',
    descriptionKey: 'exercises.items.51.description',
    categoryKey: 'exercises.categories.Баланс',
    duration: '10 мин',
    difficultyKey: 'exercises.difficulty.Продвинутый',
  },
  {
    id: '52',
    titleKey: 'exercises.items.52.title',
    descriptionKey: 'exercises.items.52.description',
    categoryKey: 'exercises.categories.Баланс',
    duration: '12 мин',
    difficultyKey: 'exercises.difficulty.Продвинутый',
  },

  // Скоростная выносливость
  {
    id: '53',
    titleKey: 'exercises.items.53.title',
    descriptionKey: 'exercises.items.53.description',
    categoryKey: 'exercises.categories.Скоростная выносливость',
    duration: '30 мин',
    difficultyKey: 'exercises.difficulty.Продвинутый',
  },
  {
    id: '54',
    titleKey: 'exercises.items.54.title',
    descriptionKey: 'exercises.items.54.description',
    categoryKey: 'exercises.categories.Скоростная выносливость',
    duration: '25 мин',
    difficultyKey: 'exercises.difficulty.Продвинутый',
  },
  {
    id: '55',
    titleKey: 'exercises.items.55.title',
    descriptionKey: 'exercises.items.55.description',
    categoryKey: 'exercises.categories.Скоростная выносливость',
    duration: '25 мин',
    difficultyKey: 'exercises.difficulty.Средний',
  },
  {
    id: '56',
    titleKey: 'exercises.items.56.title',
    descriptionKey: 'exercises.items.56.description',
    categoryKey: 'exercises.categories.Скоростная выносливость',
    duration: '30 мин',
    difficultyKey: 'exercises.difficulty.Продвинутый',
  },
  {
    id: '57',
    titleKey: 'exercises.items.57.title',
    descriptionKey: 'exercises.items.57.description',
    categoryKey: 'exercises.categories.Скоростная выносливость',
    duration: '20 мин',
    difficultyKey: 'exercises.difficulty.Продвинутый',
  },

  // Восстановление
  {
    id: '58',
    titleKey: 'exercises.items.58.title',
    descriptionKey: 'exercises.items.58.description',
    categoryKey: 'exercises.categories.Восстановление',
    duration: '20 мин',
    difficultyKey: 'exercises.difficulty.Начинающий',
  },
  {
    id: '59',
    titleKey: 'exercises.items.59.title',
    descriptionKey: 'exercises.items.59.description',
    categoryKey: 'exercises.categories.Восстановление',
    duration: '15 мин',
    difficultyKey: 'exercises.difficulty.Средний',
  },
  {
    id: '60',
    titleKey: 'exercises.items.60.title',
    descriptionKey: 'exercises.items.60.description',
    categoryKey: 'exercises.categories.Восстановление',
    duration: '20 мин',
    difficultyKey: 'exercises.difficulty.Начинающий',
  },
  {
    id: '61',
    titleKey: 'exercises.items.61.title',
    descriptionKey: 'exercises.items.61.description',
    categoryKey: 'exercises.categories.Восстановление',
    duration: '30 мин',
    difficultyKey: 'exercises.difficulty.Средний',
  },
  {
    id: '62',
    titleKey: 'exercises.items.62.title',
    descriptionKey: 'exercises.items.62.description',
    categoryKey: 'exercises.categories.Восстановление',
    duration: '25 мин',
    difficultyKey: 'exercises.difficulty.Начинающий',
  },
  {
    id: '63',
    titleKey: 'exercises.items.63.title',
    descriptionKey: 'exercises.items.63.description',
    categoryKey: 'exercises.categories.Восстановление',
    duration: '20 мин',
    difficultyKey: 'exercises.difficulty.Начинающий',
  },
  {
    id: '64',
    titleKey: 'exercises.items.64.title',
    descriptionKey: 'exercises.items.64.description',
    categoryKey: 'exercises.categories.Восстановление',
    duration: '15 мин',
    difficultyKey: 'exercises.difficulty.Начинающий',
  },
  {
    id: '65',
    titleKey: 'exercises.items.65.title',
    descriptionKey: 'exercises.items.65.description',
    categoryKey: 'exercises.categories.Восстановление',
    duration: '7 мин',
    difficultyKey: 'exercises.difficulty.Средний',
  }
];

export const getExerciseTitle = (exerciseId: string): string => {
  const exercise = exercisesData.find(e => e.id === exerciseId);
  return exercise ? exercise.titleKey : `Упражнение #${exerciseId}`;
};

export const categories = ['Выносливость', 'Взрывная скорость', 'Разминка', 'Растяжка', 'Ловкость', 'Сила', 'Баланс', 'Скоростная выносливость', 'Восстановление'];