const HOCKEY_IQ_100 = [
  [1, 'iq_youth_001', 'The opponent starts an attack through the center. What should the center do?', 'Команда соперника начинает атаку через центр. Что должен делать центральный нападающий?', [
    ['Skate to the opponent\'s net', 'Уехать к воротам соперника'],
    ['Return to the center of your zone and help the defensemen', 'Вернуться в центр своей зоны и помогать защитникам'],
    ['Stand by the boards', 'Стоять у борта'],
    ['Change lines for no reason', 'Меняться без причины'],
  ], 1],
  [1, 'iq_youth_002', 'An opponent behind the net tries to score with a lacrosse-style wrap. What should the goalie do?', 'Игрок соперника за воротами пытается забить лакросс. Что должен делать вратарь?', [
    ['Stay tight to the far post and watch the stick', 'Прижаться к дальней штанге и следить за клюшкой'],
    ['Watch the crowd', 'Смотреть на зрителей'],
    ['Skate out to the center of the zone', 'Выкатиться в центр зоны'],
    ['Lie face down on the ice', 'Лечь на лед лицом вниз'],
  ], 0],
  [1, 'iq_youth_003', 'You are a defenseman facing a 2-on-1 rush. What matters most?', 'Вы защитник, против вас выходят два соперника. Что важнее?', [
    ['Attack the puck carrier immediately', 'Сразу атаковать игрока с шайбой'],
    ['Take away the pass', 'Перекрыть передачу'],
    ['Skate to the bench for a line change', 'Уехать на смену'],
    ['Watch only the puck', 'Смотреть только на шайбу'],
  ], 1],
  [1, 'iq_youth_004', 'You are a winger and the first player entering the offensive zone. What should you do?', 'Ты крайний нападающий и первым входишь в чужую зону. Что делать?', [
    ['Pressure the defenseman with the puck', 'Давить на защитника с шайбой'],
    ['Skate straight to the bench', 'Сразу ехать на скамейку'],
    ['Stand at the blue line', 'Стоять у синей линии'],
    ['Skate in circles', 'Кататься кругами'],
  ], 0],
  [1, 'iq_youth_005', 'Your team is on the power play. Where is the center usually positioned?', 'Команда играет в большинстве. Где обычно находится центральный нападающий?', [
    ['In front of the net', 'Перед воротами'],
    ['At your own blue line', 'На своей синей линии'],
    ['On the bench', 'На скамейке'],
    ['Behind your own net', 'За воротами своей команды'],
  ], 0],
  [1, 'iq_youth_006', 'You lost the puck in the offensive zone. What should you do next?', 'Ты потерял шайбу в чужой зоне. Что делать дальше?', [
    ['Immediately join the forecheck', 'Немедленно вступить в отбор'],
    ['Skate back slowly', 'Медленно ехать назад'],
    ['Argue with the referee', 'Спорить с судьей'],
    ['Look at the coach', 'Смотреть на тренера'],
  ], 0],
  [1, 'iq_youth_007', 'The center lost the faceoff. What comes next?', 'Центральный проиграл вбрасывание. Что дальше?', [
    ['Help on defense right away', 'Сразу помогать в обороне'],
    ['Skate into the attack', 'Уехать в атаку'],
    ['Stop moving', 'Остановиться'],
    ['Take off your helmet', 'Снять шлем'],
  ], 0],
  [1, 'iq_youth_008', 'The puck is along the boards in your zone. What should the second player do?', 'Шайба у борта в вашей зоне. Что должен делать второй игрок?', [
    ['Support your partner nearby', 'Поддержать партнера рядом'],
    ['Skate to the opponent\'s net', 'Уехать к чужим воротам'],
    ['Stand still', 'Стоять без движения'],
    ['Watch the stands', 'Смотреть на трибуны'],
  ], 0],
  [1, 'iq_youth_009', 'What is most important on a 3-on-2 rush?', 'Что самое важное в атаке 3 в 2?', [
    ['Stretch the defense with passes', 'Растянуть оборону передачами'],
    ['Everyone skate to the same spot', 'Всем ехать в одну точку'],
    ['Shoot from any position', 'Бросать из любого положения'],
    ['Stop at the blue line', 'Остановиться у синей линии'],
  ], 0],
  [1, 'iq_youth_010', 'After a shot the puck bounced in front of the net. What should the goalie do?', 'После броска шайба отскочила перед воротами. Что должен делать вратарь?', [
    ['Find the puck and cover it', 'Найти шайбу и накрыть ее'],
    ['Skate behind the net', 'Уехать за ворота'],
    ['Look at the coach', 'Смотреть на тренера'],
    ['Raise the stick in the air', 'Поднять клюшку вверх'],
  ], 0],
  [1, 'iq_youth_011', 'When is the best time to change lines?', 'Когда лучше делать смену?', [
    ['When your team controls the puck', 'Когда команда контролирует шайбу'],
    ['When the opponent is attacking', 'Когда соперник атакует'],
    ['When the puck is in front of the net', 'Когда шайба перед воротами'],
    ['During a dangerous scoring chance', 'Во время опасного момента'],
  ], 0],
  [1, 'iq_youth_012', 'What should a defenseman do when under heavy forecheck pressure?', 'Что должен делать защитник, если его активно прессингуют?', [
    ['Make a quick, accurate first pass', 'Быстро отдать точный первый пас'],
    ['Stand still with the puck', 'Стоять с шайбой'],
    ['Shoot the puck to the middle of the zone', 'Бросать шайбу в центр зоны'],
    ['Fall to the ice', 'Падать на лед'],
  ], 0],
  [1, 'iq_youth_013', 'What is important to do when you don\'t have the puck?', 'Что важно делать без шайбы?', [
    ['Get open for a pass', 'Открыться под передачу'],
    ['Stand in one spot', 'Стоять на месте'],
    ['Look at the ceiling', 'Смотреть на потолок'],
    ['Hold the stick with one hand only', 'Держать клюшку одной рукой'],
  ], 0],
  [1, 'iq_youth_014', 'Which breakout is considered the most reliable?', 'Какой выход из зоны считается самым надежным?', [
    ['With a short, accurate pass', 'Через короткий точный пас'],
    ['A blind dump', 'Слепой выброс'],
    ['A pass through the middle of your zone', 'Передача через центр своей зоны'],
    ['Losing the puck', 'Потеря шайбы'],
  ], 0],
  [1, 'iq_youth_015', 'What is most important on the penalty kill?', 'Что главное в меньшинстве?', [
    ['Block passing lanes', 'Перекрывать линии передач'],
    ['Attack constantly', 'Постоянно атаковать'],
    ['Skate without a structure', 'Кататься без схемы'],
    ['Play only along the boards', 'Играть только у бортов'],
  ], 0],
  [1, 'iq_youth_016', 'When can a defenseman join the rush?', 'Когда защитнику можно подключаться в атаку?', [
    ['When his partner covers his position', 'Когда партнер страхует его позицию'],
    ['Always', 'Всегда'],
    ['Never', 'Никогда'],
    ['Only in overtime', 'Только в овертайме'],
  ], 0],
  [1, 'iq_youth_017', 'Why is a pass through the slot dangerous?', 'Почему опасна передача через пятак?', [
    ['It can lead to a goal', 'Может привести к голу'],
    ['It is always illegal', 'Она всегда запрещена'],
    ['Officials cannot see it', 'Ее не видно судьям'],
    ['It slows the game down', 'Она замедляет игру'],
  ], 0],
  [1, 'iq_youth_018', 'When should a goalie play the puck behind the net?', 'Когда вратарю стоит играть клюшкой за воротами?', [
    ['To help defensemen start the breakout', 'Чтобы помочь защитникам начать атаку'],
    ['To rest', 'Чтобы отдохнуть'],
    ['To argue with officials', 'Чтобы спорить с судьями'],
    ['To leave the ice', 'Чтобы уйти со льда'],
  ], 0],
  [1, 'iq_youth_019', 'Why does a forward drive to the far post?', 'Зачем нападающий едет на дальнюю штангу?', [
    ['For rebounds and one-timers', 'Для добивания и замыкания передачи'],
    ['To rest', 'Чтобы отдохнуть'],
    ['To stay out of the play', 'Чтобы не участвовать в игре'],
    ['To get in a teammate\'s way', 'Чтобы мешать партнеру'],
  ], 0],
  [1, 'iq_youth_020', 'What should a defenseman do before shooting from the point?', 'Что должен делать защитник перед броском от синей линии?', [
    ['Check for traffic in front of the net', 'Посмотреть, есть ли трафик перед воротами'],
    ['Close his eyes', 'Закрыть глаза'],
    ['Shoot straight into the boards', 'Бросать сразу в борт'],
    ['Dekes backward', 'Делать финт назад'],
  ], 0],
  [1, 'iq_youth_021', 'Who should battle first for the puck after a faceoff?', 'Кто должен первым бороться за подбор после вбрасывания?', [
    ['The nearest player', 'Ближайший игрок'],
    ['Only the goalie', 'Только вратарь'],
    ['Only the defenseman', 'Только защитник'],
    ['No one', 'Никто'],
  ], 0],
  [1, 'iq_youth_022', 'Why is puck control important?', 'Почему важно контролировать шайбу?', [
    ['The opponent cannot attack without the puck', 'Соперник не может атаковать без шайбы'],
    ['It looks good', 'Это красиво выглядит'],
    ['Officials award points for it', 'Судьи дают очки'],
    ['You can skate less', 'Можно меньше кататься'],
  ], 0],
  [1, 'iq_youth_023', 'What matters most in a corner battle?', 'Что главное в борьбе в углу?', [
    ['Body position and stick placement', 'Положение корпуса и клюшки'],
    ['A high shot', 'Высокий бросок'],
    ['Skating backward only', 'Катание спиной'],
    ['Jumping', 'Прыжки'],
  ], 0],
  [1, 'iq_youth_024', 'What is the best way to get open?', 'Как лучше открываться?', [
    ['Move into open space', 'В свободное пространство'],
    ['Skate behind a teammate\'s back', 'За спину партнеру'],
    ['Into a blind corner', 'В угол без обзора'],
    ['By standing still', 'Стоя на месте'],
  ], 0],
  [1, 'iq_youth_025', 'What should a forward do after taking a shot?', 'Что должен делать нападающий после броска?', [
    ['Go to the net for a rebound', 'Искать добивание'],
    ['Change lines immediately', 'Уезжать на смену сразу'],
    ['Stand still', 'Стоять на месте'],
    ['Watch the scoreboard', 'Смотреть на табло'],
  ], 0],
  [2, 'iq_youth_026', 'What is most important for a defenseman in the slot?', 'Что главное для защитника на пятаке?', [
    ['Prevent opponents from getting to rebounds', 'Не дать сопернику добить шайбу'],
    ['Watch only the goalie', 'Смотреть только на вратаря'],
    ['Stay far from the net', 'Стоять далеко от ворот'],
    ['Play without a stick', 'Играть без клюшки'],
  ], 0],
  [2, 'iq_youth_027', 'What is the best way to enter the zone?', 'Как лучше входить в зону?', [
    ['With puck control', 'С контролем шайбы'],
    ['Without speed', 'Без скорости'],
    ['Through the middle with no support', 'Через центр без поддержки'],
    ['Skating backward into the zone', 'Спиной вперед'],
  ], 0],
  [2, 'iq_youth_028', 'When is a backhand shot useful?', 'Когда полезен бросок с неудобной?', [
    ['When there is no time to move the puck to the forehand', 'Когда нет времени перекладывать шайбу'],
    ['Never', 'Никогда'],
    ['Only in practice', 'Только на тренировке'],
    ['Only for defensemen', 'Только защитникам'],
  ], 0],
  [2, 'iq_youth_029', 'Why is the center important in attack?', 'Почему центр важен в атаке?', [
    ['He connects the whole line', 'Он связывает всю пятерку'],
    ['He always stands still', 'Он всегда стоит на месте'],
    ['He never plays defense', 'Он не играет в обороне'],
    ['He never makes passes', 'Он не делает передачи'],
  ], 0],
  [2, 'iq_youth_030', 'What matters in 1-on-1 defensive play?', 'Что важно при игре 1 в 1 в защите?', [
    ['Control gap and angle', 'Держать дистанцию и направление'],
    ['Jump on the opponent immediately', 'Сразу прыгать на соперника'],
    ['Skate backward with no control', 'Катиться назад без контроля'],
    ['Watch the stands', 'Смотреть на трибуны'],
  ], 0],
  [2, 'iq_youth_031', 'Your line had a long offensive shift. The opponent defenseman recovered the puck behind the net but looks tired. Your line has been on the ice a long time too. What is best?', 'Ваша пятерка провела длинную атаку. Защитник соперника подобрал шайбу за воротами, но выглядит уставшим. Ваше звено тоже долго на льду. Что лучше сделать?', [
    ['One forward keeps pressing while the others change', 'Один нападающий остается давить, остальные меняются'],
    ['The whole line changes at once', 'Вся пятерка сразу едет на смену'],
    ['Keep forechecking aggressively with the full line', 'Продолжать агрессивный форчек всей пятеркой'],
    ['Fall back to the neutral zone with no pressure', 'Полностью откатиться в среднюю зону без давления'],
  ], 0],
  [2, 'iq_youth_032', 'Why is a pass backward sometimes useful?', 'Почему иногда полезен пас назад?', [
    ['To keep possession', 'Чтобы сохранить контроль шайбы'],
    ['To lose momentum', 'Чтобы потерять темп'],
    ['To stop play', 'Чтобы остановить игру'],
    ['To avoid attacking', 'Чтобы избежать атаки'],
  ], 0],
  [2, 'iq_youth_033', 'What matters when blocking a shot?', 'Что важно при блокировке броска?', [
    ['Block the puck\'s path', 'Перекрыть траекторию шайбы'],
    ['Turn your back', 'Отвернуться спиной'],
    ['Jump upward', 'Прыгнуть вверх'],
    ['Look down', 'Смотреть вниз'],
  ], 0],
  [2, 'iq_youth_034', 'How should a defenseman play against a fast forward?', 'Как защитнику играть против быстрого нападающего?', [
    ['Do not give him open ice', 'Не давать свободный лед'],
    ['Keep skating forward without stopping', 'Катиться вперед без остановки'],
    ['Stand still', 'Стоять на месте'],
    ['Play too tight every time', 'Играть слишком близко'],
  ], 0],
  [2, 'iq_youth_035', 'When is a one-timer most effective?', 'Когда эффективен бросок в касание?', [
    ['When the goalie cannot get set in time', 'Когда вратарь не успевает переместиться'],
    ['When the puck is stationary', 'Когда шайба стоит'],
    ['When the shooter is not ready', 'Когда игрок не готов'],
    ['Only in practice', 'Только на тренировке'],
  ], 0],
  [2, 'iq_youth_036', 'Why is communication on the ice important?', 'Почему важно разговаривать на льду?', [
    ['It helps teammates make decisions faster', 'Это помогает партнерам быстрее принимать решения'],
    ['It distracts the opponent', 'Это мешает сопернику'],
    ['Officials like it', 'Это нравится судьям'],
    ['It replaces skating', 'Это заменяет катание'],
  ], 0],
  [2, 'iq_youth_037', 'How should you play a 2-on-0 rush?', 'Как лучше разыграть выход 2 в 0?', [
    ['Make the goalie move with a pass', 'Заставить вратаря двигаться передачей'],
    ['Shoot from far out', 'Бросить издалека'],
    ['Stop in front of the net', 'Остановиться перед воротами'],
    ['Lose the puck', 'Потерять шайбу'],
  ], 0],
  [2, 'iq_youth_038', 'Why do forwards use the space behind the net?', 'Почему нападающие используют пространство за воротами?', [
    ['To stretch the defense', 'Чтобы растянуть оборону'],
    ['To hide from the play', 'Чтобы спрятаться'],
    ['To stop the play', 'Чтобы остановить игру'],
    ['To avoid shooting', 'Чтобы не бросать'],
  ], 0],
  [2, 'iq_youth_039', 'Why is it important to stay calm?', 'Почему важно сохранять спокойствие?', [
    ['It helps you make better decisions', 'Это помогает принимать правильные решения'],
    ['It makes the puck faster', 'Это ускоряет шайбу'],
    ['It affects the ice', 'Это влияет на лед'],
    ['It makes the net smaller', 'Это уменьшает размеры ворот'],
  ], 0],
  [2, 'iq_youth_040', 'What should a defenseman do at the offensive blue line?', 'Что должен делать защитник у синей линии?', [
    ['Keep the puck in the zone', 'Удерживать шайбу в зоне'],
    ['Always retreat', 'Всегда уходить назад'],
    ['Ignore teammates', 'Не смотреть на партнеров'],
    ['Stand in the middle only', 'Стоять в центре'],
  ], 0],
  [2, 'iq_youth_041', 'What makes a rebound dangerous?', 'Что делает добивание опасным?', [
    ['The goalie does not always control the rebound', 'Вратарь не всегда контролирует отскок'],
    ['The referee cannot see the puck', 'Судья не видит шайбу'],
    ['The player stands still', 'Игрок стоит без движения'],
    ['The puck becomes lighter', 'Шайба становится легче'],
  ], 0],
  [2, 'iq_youth_042', 'Why is changing the direction of attack useful?', 'Почему полезно менять направление атаки?', [
    ['It creates open areas', 'Это создает свободные зоны'],
    ['It slows the game down', 'Это замедляет игру'],
    ['It hurts your own team', 'Это мешает своим'],
    ['It tires the officials', 'Это утомляет судей'],
  ], 0],
  [2, 'iq_youth_043', 'What matters on an offensive-zone faceoff?', 'Что важно при вбрасывании в чужой зоне?', [
    ['Win puck possession quickly', 'Быстро получить контроль шайбы'],
    ['Skate back immediately', 'Сразу уехать назад'],
    ['Do not move', 'Не двигаться'],
    ['Watch the scoreboard', 'Смотреть на табло'],
  ], 0],
  [2, 'iq_youth_044', 'What does it mean to cover for a teammate?', 'Что значит страховать партнера?', [
    ['Fill his position when he joins the rush', 'Закрывать его позицию при подключении'],
    ['Stand next to him without moving', 'Стоять рядом без движения'],
    ['Copy his exact route', 'Повторять его маршрут'],
    ['Only play offense', 'Играть только вперед'],
  ], 0],
  [2, 'iq_youth_045', 'If a defenseman loses position, what should he do?', 'Если защитник потерял позицию, что делать?', [
    ['Get back on defense quickly', 'Быстро возвращаться в оборону'],
    ['Stop skating', 'Остановиться'],
    ['Watch only the puck', 'Смотреть на шайбу'],
    ['Argue with a teammate', 'Спорить с партнером'],
  ], 0],
  [2, 'iq_youth_046', 'Why do players often shoot low?', 'Почему часто бросают низом?', [
    ['For deflections and rebounds', 'Для рикошетов и добиваний'],
    ['Because high shots are illegal', 'Потому что нельзя бросать верхом'],
    ['It is slower', 'Это медленнее'],
    ['It is easier for officials', 'Это легче судить'],
  ], 0],
  [2, 'iq_youth_047', 'When is a long pass especially useful?', 'Когда длинный пас особенно полезен?', [
    ['On a fast counterattack', 'При быстрой контратаке'],
    ['In a crowd of players', 'В толпе игроков'],
    ['With no target', 'Без адресата'],
    ['During a line change', 'При смене звена'],
  ], 0],
  [2, 'iq_youth_048', 'Why is movement without the puck important?', 'Почему движение без шайбы важно?', [
    ['It creates passing options', 'Оно создает варианты для передачи'],
    ['It gets in teammates\' way', 'Оно мешает своим'],
    ['It does not affect the game', 'Оно не влияет на игру'],
    ['It is only for defensemen', 'Оно только для защитников'],
  ], 0],
  [2, 'iq_youth_049', 'When can a shot from a sharp angle be useful?', 'Когда бросок с острого угла может быть полезен?', [
    ['For an unexpected rebound', 'Для неожиданного отскока'],
    ['Never', 'Никогда'],
    ['Only on the power play', 'Только в большинстве'],
    ['Only on the penalty kill', 'Только в меньшинстве'],
  ], 0],
  [2, 'iq_youth_050', 'Why is screening the goalie important?', 'Почему важно закрывать обзор вратарю?', [
    ['It is harder for him to see the shot', 'Ему сложнее увидеть бросок'],
    ['The referee cannot see the puck', 'Судья не видит шайбу'],
    ['It makes the attack look better', 'Это украшает атаку'],
    ['The goalie stops moving', 'Вратарь перестает двигаться'],
  ], 0],
  [3, 'iq_youth_051', 'What helps you intercept passes?', 'Что помогает перехватывать передачи?', [
    ['Reading the play', 'Чтение игры'],
    ['Luck alone', 'Случайность'],
    ['Skating slowly', 'Медленное катание'],
    ['Playing without a stick', 'Игра без клюшки'],
  ], 0],
  [3, 'iq_youth_052', 'How do you pin an opponent along the boards correctly?', 'Как правильно прижимать соперника к борту?', [
    ['Use your body and stick while controlling the puck', 'Корпусом и клюшкой контролируя шайбу'],
    ['Push him in the back', 'Толкая в спину'],
    ['With your eyes closed', 'Закрывая глаза'],
    ['With your hands and no stick', 'Руками без клюшки'],
  ], 0],
  [3, 'iq_youth_053', 'What matters when a defenseman comes out from behind the net?', 'Что важно при выходе защитника из-за ворот?', [
    ['Look up and find a pass', 'Поднять голову и найти пас'],
    ['Look only at the ice', 'Смотреть только вниз'],
    ['Skate slowly', 'Катиться медленно'],
    ['Shoot the puck immediately', 'Сразу бросать шайбу'],
  ], 0],
  [3, 'iq_youth_054', 'Why do teams sometimes slow the game down?', 'Почему команды иногда замедляют игру?', [
    ['To keep possession and energy', 'Чтобы сохранить контроль и силы'],
    ['To lose the puck', 'Чтобы потерять шайбу'],
    ['To stop the game', 'Чтобы остановить матч'],
    ['To avoid attacking', 'Чтобы не атаковать'],
  ], 0],
  [3, 'iq_youth_055', 'Who is a second-wave player?', 'Кто такой игрок второго темпа?', [
    ['A player who joins the attack later', 'Игрок, подключающийся позже к атаке'],
    ['The backup goalie', 'Запасной вратарь'],
    ['A referee', 'Судья'],
    ['The slowest player', 'Самый медленный игрок'],
  ], 0],
  [3, 'iq_youth_056', 'Why are quick short passes effective?', 'Почему быстрые короткие передачи эффективны?', [
    ['They are harder for opponents to steal', 'Сопернику сложнее отбирать шайбу'],
    ['They are always slow', 'Они всегда медленные'],
    ['They hurt the attack', 'Они мешают атаке'],
    ['They are only for defensemen', 'Они нужны только защитникам'],
  ], 0],
  [3, 'iq_youth_057', 'What should a goalie do after making a save?', 'Что должен делать вратарь после сейва?', [
    ['Quickly track the puck', 'Быстро искать шайбу'],
    ['Look at the scoreboard', 'Смотреть на табло'],
    ['Skate to the boards', 'Уезжать к борту'],
    ['Take off his glove', 'Снимать ловушку'],
  ], 0],
  [3, 'iq_youth_058', 'When is an attack through the middle especially dangerous?', 'Когда атака через центр особенно опасна?', [
    ['When there is speed and support', 'Когда есть скорость и поддержка'],
    ['When one player is alone', 'Когда игрок один'],
    ['When everyone stands still', 'Когда все стоят'],
    ['When there is no puck', 'Когда нет шайбы'],
  ], 0],
  [3, 'iq_youth_059', 'What helps you make decisions faster?', 'Что помогает быстрее принимать решения?', [
    ['Constantly scanning the ice', 'Постоянный просмотр площадки'],
    ['Watch only the puck', 'Смотреть только на шайбу'],
    ['Skating slowly', 'Медленное катание'],
    ['Play without talking', 'Играть без общения'],
  ], 0],
  [3, 'iq_youth_060', 'What does a good captain do?', 'Что делает хороший капитан?', [
    ['Supports the team and leads by example', 'Поддерживает команду и ведет примером'],
    ['Plays only offense', 'Играет только в атаке'],
    ['Yells at everyone', 'Кричит на всех'],
    ['Never plays defense', 'Не играет в обороне'],
  ], 0],
  [3, 'iq_youth_061', 'What helps you escape forecheck pressure?', 'Что помогает выйти из-под прессинга?', [
    ['Moving the puck quickly', 'Быстрое движение шайбы'],
    ['Holding the puck for a long time', 'Долгое удержание шайбы'],
    ['Stopping along the boards', 'Остановка у борта'],
    ['Playing alone', 'Игра в одиночку'],
  ], 0],
  [3, 'iq_youth_062', 'Why can you not hesitate at the blue line?', 'Почему нельзя медлить на синей линии?', [
    ['You can lose the zone', 'Можно потерять зону'],
    ['The referee will stop play', 'Судья остановит игру'],
    ['The goalie will get tired', 'Вратарь устанет'],
    ['The ice will get worse', 'Лед станет хуже'],
  ], 0],
  [3, 'iq_youth_063', 'Why is a shot right after a pass dangerous?', 'Почему опасен бросок сразу после паса?', [
    ['The goalie is not set in time', 'Вратарь не успевает подготовиться'],
    ['It is always weak', 'Он всегда слабый'],
    ['It is hard to execute', 'Его сложно выполнить'],
    ['The referee will disallow the goal', 'Судья не засчитает гол'],
  ], 0],
  [3, 'iq_youth_064', 'Who should get back first after losing the puck?', 'Кто первым должен возвращаться после потери шайбы?', [
    ['The nearest player', 'Ближайший игрок'],
    ['Only the defenseman', 'Только защитник'],
    ['Only the center', 'Только центр'],
    ['Only the goalie', 'Только вратарь'],
  ], 0],
  [3, 'iq_youth_065', 'How should a defenseman play against a hard shooter?', 'Как защитнику играть против игрока с сильным броском?', [
    ['Reduce his time and space to shoot', 'Сокращать время на бросок'],
    ['Give him open space', 'Давать свободное пространство'],
    ['Stand far away', 'Стоять далеко'],
    ['Watch only the goalie', 'Смотреть только на вратаря'],
  ], 0],
  [3, 'iq_youth_066', 'Why is the puck often moved to the corner in defense?', 'Почему шайбу часто уводят в угол в обороне?', [
    ['There is less danger to the net', 'Там меньше опасность для ворот'],
    ['It is easier to score there', 'Там легче забить'],
    ['Officials cannot see the play', 'Судья не видит игру'],
    ['The ice is slower there', 'Там медленнее лед'],
  ], 0],
  [3, 'iq_youth_067', 'What does a forward do in front of the net?', 'Что делает нападающий перед воротами?', [
    ['Creates traffic and hunts rebounds', 'Создает трафик и ищет добивание'],
    ['Stands with his back to the play', 'Стоит спиной к игре'],
    ['Does not move', 'Не двигается'],
    ['Skates to the boards', 'Уходит к борту'],
  ], 0],
  [3, 'iq_youth_068', 'Why is it important to play with your head up?', 'Почему важно играть с поднятой головой?', [
    ['To see teammates and opponents', 'Чтобы видеть партнеров и соперников'],
    ['To skate faster', 'Чтобы быстрее кататься'],
    ['To make the puck lighter', 'Чтобы шайба была легче'],
    ['So officials can see you', 'Чтобы судья видел игрока'],
  ], 0],
  [3, 'iq_youth_069', 'What matters most after winning a PK faceoff?', 'Что главное после выигранного вбрасывания в меньшинстве?', [
    ['Clear the puck out of the zone', 'Вывести шайбу из зоны'],
    ['Try to deke through everyone', 'Идти в обводку'],
    ['Stand still', 'Стоять на месте'],
    ['Take a long pause', 'Делать длинную паузу'],
  ], 0],
  [3, 'iq_youth_070', 'Why is it important to pressure opposing defensemen?', 'Почему важно давить на защитников соперника?', [
    ['It can force a mistake', 'Это может привести к ошибке'],
    ['It stops the game', 'Это останавливает игру'],
    ['It hurts your team', 'Это мешает своим'],
    ['It does not affect the game', 'Это не влияет на матч'],
  ], 0],
  [3, 'iq_youth_071', 'When is a touch pass useful?', 'Когда полезен пас в касание?', [
    ['To develop the attack quickly', 'Для быстрого развития атаки'],
    ['Only in defense', 'Только в обороне'],
    ['When there are no teammates', 'Когда нет партнеров'],
    ['When the player is standing still', 'Когда игрок стоит'],
  ], 0],
  [3, 'iq_youth_072', 'What should the center do in front of his own net?', 'Что должен делать центр у своих ворот?', [
    ['Help defensemen cover the slot', 'Помогать защитникам закрывать пятак'],
    ['Wait for a pass up ice', 'Ждать передачу вперед'],
    ['Stand by the boards', 'Стоять у борта'],
    ['Skate to the neutral zone', 'Уезжать в среднюю зону'],
  ], 0],
  [3, 'iq_youth_073', 'Why is criss-cross movement by forwards effective?', 'Почему перекрестное движение нападающих эффективно?', [
    ['It confuses defenders', 'Оно путает защитников'],
    ['It slows the attack', 'Оно замедляет атаку'],
    ['It hurts your own team', 'Оно мешает своим'],
    ['It is illegal', 'Оно запрещено'],
  ], 0],
  [3, 'iq_youth_074', 'What matters when battling for a loose puck?', 'Что важно при подборе шайбы?', [
    ['Decide quickly what to do next', 'Быстро принять решение'],
    ['Hold the puck for a long time', 'Долго держать шайбу'],
    ['Look down', 'Смотреть вниз'],
    ['Stand still', 'Стоять на месте'],
  ], 0],
  [3, 'iq_youth_075', 'Why do players change speed?', 'Почему игроки меняют скорость?', [
    ['To beat an opponent', 'Чтобы обыграть соперника'],
    ['To get tired faster', 'Чтобы устать быстрее'],
    ['To stop skating', 'Чтобы остановиться'],
    ['To lose the puck', 'Чтобы потерять шайбу'],
  ], 0],
  [4, 'iq_youth_076', 'There are 40 seconds left. You lead by one goal. The opponent is playing 6-on-5. Their defenseman has the puck at the blue line and your winger can jump for a steal. What is best?', 'До конца матча 40 секунд. Вы ведете в одну шайбу. Соперник играет 6 на 5. Шайба у их защитника на синей линии, а ваш крайний может выбежать на перехват. Что лучше?', [
    ['Press only with a controlled angle to take the puck', 'Атаковать только при уверенном угле отбора'],
    ['Fly at the puck aggressively right away', 'Сразу агрессивно вылетать на шайбу'],
    ['Collapse completely to the net', 'Полностью опуститься к воротам'],
    ['Track only the net-front player', 'Следить только за игроком перед воротами'],
  ], 0],
  [4, 'iq_youth_077', 'When can a goalie come far out of his net?', 'Когда вратарь может выйти далеко из ворот?', [
    ['To intercept the puck and help the defense', 'Чтобы перехватить шайбу и помочь защите'],
    ['Always', 'Всегда'],
    ['Never', 'Никогда'],
    ['Only after a goal', 'Только после гола'],
  ], 0],
  [4, 'iq_youth_078', 'What matters for a successful rebound attempt?', 'Что важно для успешного добивания?', [
    ['Quick reaction', 'Быстрая реакция'],
    ['Slow movement', 'Медленное движение'],
    ['A big wind-up', 'Высокий замах'],
    ['Stand far from the net', 'Стоять далеко от ворот'],
  ], 0],
  [4, 'iq_youth_079', 'Why is second-player support important?', 'Почему важна поддержка второго игрока?', [
    ['It creates extra options', 'Она дает дополнительные варианты'],
    ['It hurts the attack', 'Она мешает атаке'],
    ['It is not needed', 'Она не нужна'],
    ['It is only for defensemen', 'Она только для защитников'],
  ], 0],
  [4, 'iq_youth_080', 'What does "reading the play" mean?', 'Что значит «читать игру»?', [
    ['Anticipate what opponents will do', 'Предугадывать действия соперника'],
    ['Watch the scoreboard', 'Смотреть на табло'],
    ['Count passes', 'Считать передачи'],
    ['Follow only the puck', 'Следить только за шайбой'],
  ], 0],
  [4, 'iq_youth_081', 'Why is it important to protect the puck with your body?', 'Почему важно уметь играть корпусом?', [
    ['It helps shield the puck', 'Это помогает защищать шайбу'],
    ['It makes the ice faster', 'Это ускоряет лед'],
    ['It is only for defensemen', 'Это нужно только защитникам'],
    ['It affects the referee', 'Это влияет на судью'],
  ], 0],
  [4, 'iq_youth_082', 'When is a breakout along the boards useful?', 'Когда полезен выход через борт?', [
    ['When the middle is covered', 'Когда центр перекрыт'],
    ['Always', 'Всегда'],
    ['Never', 'Никогда'],
    ['Only on the power play', 'Только в большинстве'],
  ], 0],
  [4, 'iq_youth_083', 'What matters when defending against a power play?', 'Что важно против большинства соперника?', [
    ['Stay compact defensively', 'Компактная оборона'],
    ['Constant dekes', 'Постоянные обводки'],
    ['Playing one-on-one everywhere', 'Игра по одному'],
    ['Slow line changes', 'Медленные смены'],
  ], 0],
  [4, 'iq_youth_084', 'What is a pass for a shot?', 'Что такое передача под бросок?', [
    ['A pass to a player in a good shooting position', 'Пас игроку в удобную позицию для броска'],
    ['A pass to the corner', 'Пас в угол'],
    ['A pass back to the goalie', 'Пас назад вратарю'],
    ['A random pass', 'Случайная передача'],
  ], 0],
  [4, 'iq_youth_085', 'Why is a deke before a shot useful?', 'Почему полезен финт перед броском?', [
    ['It can move the goalie or a defender', 'Он может сместить вратаря или защитника'],
    ['It always slows the attack', 'Он всегда замедляет атаку'],
    ['It is illegal', 'Он запрещен'],
    ['It is only for defensemen', 'Он нужен только защитникам'],
  ], 0],
  [4, 'iq_youth_086', 'After blocking a shot, a player should:', 'После блокировки броска игрок должен:', [
    ['Immediately look for the puck', 'Сразу искать шайбу'],
    ['Stand still', 'Стоять на месте'],
    ['Look at the referee', 'Смотреть на судью'],
    ['Leave the ice', 'Уезжать со льда'],
  ], 0],
  [4, 'iq_youth_087', 'How do forwards help defensemen?', 'Как нападающие помогают защитникам?', [
    ['Backcheck and get open for a pass', 'Возвращаются назад и открываются под пас'],
    ['Stay in the offensive zone', 'Стоят в атаке'],
    ['Do not play defense', 'Не участвуют в обороне'],
    ['Play only along the boards', 'Играют только у бортов'],
  ], 0],
  [4, 'iq_youth_088', 'What helps against heavy forechecking?', 'Что помогает против сильного прессинга?', [
    ['Quick decisions and puck movement', 'Быстрые решения и движение'],
    ['Long puck possession', 'Долгое владение шайбой'],
    ['Playing alone', 'Игра в одиночку'],
    ['Skating slowly', 'Медленное катание'],
  ], 0],
  [4, 'iq_youth_089', 'When is a stick deflection useful?', 'Когда полезно подставление клюшки?', [
    ['To redirect the puck', 'Для изменения направления шайбы'],
    ['Only in defense', 'Только в защите'],
    ['Never', 'Никогда'],
    ['Only in practice', 'Только на тренировке'],
  ], 0],
  [4, 'iq_youth_090', 'What matters when attacking along the boards?', 'Что важно при атаке через борт?', [
    ['Support from a nearby teammate', 'Поддержка партнера рядом'],
    ['Playing alone', 'Игра в одиночку'],
    ['Stopping movement', 'Остановка движения'],
    ['Passing back to the goalie', 'Передача назад вратарю'],
  ], 0],
  [4, 'iq_youth_091', 'What matters for a goalie on a breakaway?', 'Что важно вратарю при выходе один в ноль?', [
    ['Keep good positioning and patience', 'Сохранять правильную позицию и терпение'],
    ['Drop to the ice immediately', 'Сразу падать на лед'],
    ['Skate backward', 'Уезжать назад'],
    ['Watch the defensemen', 'Смотреть на защитников'],
  ], 0],
  [4, 'iq_youth_092', 'What matters on a fast transition to offense?', 'Что важно при быстром переходе в атаку?', [
    ['Speed of decision-making', 'Скорость принятия решений'],
    ['Slow passes', 'Медленные передачи'],
    ['Long puck possession', 'Долгий контроль шайбы'],
    ['Stopping at the blue line', 'Остановка у синей линии'],
  ], 0],
  [4, 'iq_youth_093', 'What does a defenseman do on the power play?', 'Что делает защитник в большинстве?', [
    ['Moves the puck and looks for a shot', 'Двигает шайбу и ищет момент для броска'],
    ['Stands still', 'Стоит без движения'],
    ['Skates to the net', 'Уходит к воротам'],
    ['Does not join the attack', 'Не участвует в атаке'],
  ], 0],
  [4, 'iq_youth_094', 'Why is traffic in front of the net dangerous?', 'Почему трафик перед воротами опасен?', [
    ['The goalie has a harder time seeing the puck', 'Вратарь хуже видит шайбу'],
    ['The referee cannot count players', 'Судья не может считать игроков'],
    ['Players get tired faster', 'Игроки устают быстрее'],
    ['The puck gets slower', 'Шайба становится медленнее'],
  ], 0],
  [4, 'iq_youth_095', 'What matters after intercepting the puck?', 'Что важно после перехвата шайбы?', [
    ['Transition quickly to offense', 'Быстро перейти в атаку'],
    ['Stop skating', 'Остановиться'],
    ['Dump the puck right away', 'Сразу выбросить шайбу'],
    ['Skate to the boards', 'Катиться к борту'],
  ], 0],
  [4, 'iq_youth_096', 'What is especially important in overtime?', 'Что особенно важно в овертайме?', [
    ['Puck control and few mistakes', 'Контроль шайбы и минимум ошибок'],
    ['Constant long shots', 'Постоянные дальние броски'],
    ['Long shifts', 'Долгие смены'],
    ['Playing without passes', 'Игра без пасов'],
  ], 0],
  [4, 'iq_youth_097', 'What should a defenseman do if an opponent screens the goalie?', 'Что делать защитнику, если соперник закрывает обзор вратарю?', [
    ['Clear the slot and tie up the opponent', 'Освободить пятак и мешать сопернику'],
    ['Stand nearby without moving', 'Стоять рядом без движения'],
    ['Look at the referee', 'Смотреть на судью'],
    ['Skate to the boards', 'Уехать к борту'],
  ], 0],
  [4, 'iq_youth_098', 'Why is team play more important than individual play?', 'Почему командная игра важнее индивидуальной?', [
    ['A line creates more chances together', 'Пятерка создает больше моментов вместе'],
    ['One player always decides the game', 'Один игрок всегда решает матч'],
    ['Passes hurt the game', 'Передачи мешают игре'],
    ['The team does not affect the result', 'Команда не влияет на результат'],
  ], 0],
  [4, 'iq_youth_099', 'What matters before taking a shot?', 'Что важно перед броском?', [
    ['Quickly read the goalie\'s position', 'Быстро оценить позицию вратаря'],
    ['Look only down at the puck', 'Смотреть только вниз'],
    ['Come to a full stop', 'Остановиться полностью'],
    ['Close your eyes', 'Закрыть глаза'],
  ], 0],
  [4, 'iq_youth_100', 'What best develops hockey IQ?', 'Что лучше всего развивает хоккейный интеллект?', [
    ['Studying the game, practice, and understanding situations', 'Анализ игры, практика и понимание ситуаций'],
    ['Strength training only', 'Только силовые тренировки'],
    ['Skating only', 'Только катание'],
    ['Watching goals only', 'Только просмотр голов'],
  ], 0],
];

module.exports = HOCKEY_IQ_100;
